/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wqa.form.main.entrer;

import java.awt.CardLayout;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JSplitPane;
import modebus.pro.NahonConvert;
import nahon.comm.faultsystem.LogCenter;
import wqa.console.io.IOManager;
import wqa.console.manager.ProcessData;
import wqa.console.system.WQAPlatform;
import wqa.form.consoleform.ConsoleDesk;
import wqa.form.log.LogPane;

/**
 *
 * @author chejf
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private ConsoleDesk work_area = new ConsoleDesk();
    private LogPane logpane = new LogPane();
    private JSplitPane chartAnddataSplit;
    public static final String timeFormat = "yyyy-MM-dd HH:mm:ss";
    
    public MainForm() {
        initComponents();
        
        chartAnddataSplit = new JSplitPane(JSplitPane.VERTICAL_SPLIT, work_area, logpane);
        chartAnddataSplit.setResizeWeight(0.5);
        chartAnddataSplit.setDividerSize(15);
        chartAnddataSplit.setOneTouchExpandable(false);
        logpane.setVisible(false);
        jButton2.setVisible(false);
        
        Label_ComNameMouseClicked(null);
        
        this.process_bar.setMaximum(100);
        this.process_bar.setMinimum(0);
        this.process_bar.setValue(0);
        
        Panel_show.setLayout(new CardLayout());
        Panel_show.add(chartAnddataSplit);
        float time = (float) WQAPlatform.GetInstance().GetManager().CollectorInstance.intergeral / 60;
        this.TextField_time.setText(NahonConvert.TimData(time, 2) + "");
        
        Date now = new Date();
        now.setTime(new Date().getTime() - 24 * 3600 * 1000);
        instance = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboBox_ComName = new javax.swing.JComboBox<>();
        Label_ComName = new javax.swing.JLabel();
        Button_Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TextField_bandrate = new javax.swing.JTextField();
        ToggleButton_Open = new javax.swing.JToggleButton();
        TextField_time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Button_Config = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        process_bar = new javax.swing.JProgressBar();
        Label_Pecent = new javax.swing.JLabel();
        Panel_show = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBox_ComName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Label_ComName.setText("串口:");
        Label_ComName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ComNameMouseClicked(evt);
            }
        });

        Button_Search.setText("搜索");
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });

        jLabel2.setText("波特率:");

        TextField_bandrate.setText("9600");

        ToggleButton_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wqa/form/main/resource/disconnect_32p.png"))); // NOI18N
        ToggleButton_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_OpenActionPerformed(evt);
            }
        });

        TextField_time.setText("1");

        jLabel1.setText("实时采样间隔:");

        jLabel3.setText("分钟");

        Button_Config.setText("设置");
        Button_Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConfigActionPerformed(evt);
            }
        });

        jButton2.setText("导出实时数据");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("日志");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        Label_Pecent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Pecent.setText("--/--");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(process_bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_ComName)
                .addGap(9, 9, 9)
                .addComponent(ComboBox_ComName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_bandrate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToggleButton_Open)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Pecent, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(TextField_time, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Config)
                .addGap(87, 87, 87)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Button_Search)
                    .addComponent(ToggleButton_Open, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_bandrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBox_ComName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_ComName)
                    .addComponent(jButton2)
                    .addComponent(TextField_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(Button_Config))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(Label_Pecent))
                .addGap(10, 10, 10)
                .addComponent(process_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_showLayout = new javax.swing.GroupLayout(Panel_show);
        Panel_show.setLayout(Panel_showLayout);
        Panel_showLayout.setHorizontalGroup(
            Panel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel_showLayout.setVerticalGroup(
            Panel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Label_ComNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ComNameMouseClicked
        
        this.ComboBox_ComName.removeAllItems();
        for (String name : IOManager.GetInstance().ListAllIO()) {
            this.ComboBox_ComName.addItem(name);
        }
        this.ComboBox_ComName.updateUI();
    }//GEN-LAST:event_Label_ComNameMouseClicked
    
    private void Switch(boolean value) throws Exception {
        if (value) {
            IOManager.GetInstance().OpenIO(ComboBox_ComName.getSelectedItem().toString(), TextField_bandrate.getText());
            ComboBox_ComName.setEnabled(!value);
            TextField_bandrate.setEnabled(!value);
            ToggleButton_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wqa/form/main/resource/connect_32p.png"))); // NOI18N
        } else {
            IOManager.GetInstance().CloseIO(ComboBox_ComName.getSelectedItem().toString());
            ComboBox_ComName.setEnabled(!value);
            TextField_bandrate.setEnabled(!value);
            ToggleButton_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wqa/form/main/resource/disconnect_32p.png"))); // NOI18N
        }
    }

    private void ToggleButton_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_OpenActionPerformed
        boolean value = ToggleButton_Open.isSelected();
        try {
            Switch(value);
        } catch (Exception ex) {
            ToggleButton_Open.setSelected(!value);
            LogCenter.Instance().SendFaultReport(Level.SEVERE, ex);
        }

    }//GEN-LAST:event_ToggleButton_OpenActionPerformed

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        if (!this.ToggleButton_Open.isSelected()) {
            this.ToggleButton_Open.setSelected(true);
            ToggleButton_OpenActionPerformed(null);
        }
        
        Button_Search.setEnabled(false);
        ProcessData ret = WQAPlatform.GetInstance().GetManager().Search();
        WQAPlatform.GetInstance().GetThreadPool().submit(() -> {
            while (!ret.isfinished) {
                java.awt.EventQueue.invokeLater(() -> {
                    process_bar.setMaximum(ret.total_len);
                    process_bar.setValue(ret.current_len);
                });

                try {
                    TimeUnit.SECONDS.sleep(1);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            java.awt.EventQueue.invokeLater(() -> {
                process_bar.setValue(0);
                work_area.Reflesh();
                Button_Search.setEnabled(true);
            });
            WQAPlatform.GetInstance().GetManager().CollectorInstance.Collect();
        });
    }//GEN-LAST:event_Button_SearchActionPerformed

    private void Button_ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConfigActionPerformed
        // TODO add your handling code here:
        try {
            String input = this.TextField_time.getText();
            WQAPlatform.GetInstance().GetManager().CollectorInstance.intergeral = (int) (Float.valueOf(input) * 60);
        } catch (Exception ex) {
            LogCenter.Instance().SendFaultReport(Level.SEVERE, "输入异常");
        }
    }//GEN-LAST:event_Button_ConfigActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = InitPaneHelper.GetDirPath(); // TODO add your handling code here:
        WQAPlatform.GetInstance().GetManager().SaveTo(path);
        LogCenter.Instance().ShowMessBox(Level.SEVERE, "导出完毕");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private int lastdivider = 320;
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        this.logpane.setVisible(jToggleButton1.isSelected());
        if (logpane.isVisible()) {
            chartAnddataSplit.setDividerLocation(lastdivider);
        } else {
            lastdivider = chartAnddataSplit.getDividerLocation();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    public static MainForm instance;
    
    public javax.swing.JProgressBar GetProcesBar() {
        return this.process_bar;
    }
    
    public JLabel GetPecentLable() {
        return this.Label_Pecent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Config;
    private javax.swing.JButton Button_Search;
    private javax.swing.JComboBox<String> ComboBox_ComName;
    private javax.swing.JLabel Label_ComName;
    private javax.swing.JLabel Label_Pecent;
    private javax.swing.JPanel Panel_show;
    private javax.swing.JTextField TextField_bandrate;
    private javax.swing.JTextField TextField_time;
    private javax.swing.JToggleButton ToggleButton_Open;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JProgressBar process_bar;
    // End of variables declaration//GEN-END:variables
}
